language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=true
  matrix:
    - TARGET=x86_64-linux-gnu
    - TARGET=i686-linux-gnu
    - TARGET=aarch64-linux-gnu
    - TARGET=x86_64-apple-darwin14
    - TARGET=x86_64-w64-mingw
    - TARGET=i686-w64-mingw
    - TARGET=x86_64-unknown-freebsd11.1
sudo: required
jobs:
  include:
    - stage: regenerate build.jl
      script: julia --color=yes build_tarballs.jl --only-buildjl
      if: tag IS present
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'
script:
  - julia --color=yes build_tarballs.jl $TARGET
deploy:
  provider: releases
  api_key:
    secure: TODO
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    tags: true
    repo: ararslan/HDF5Builder
